name: Pipeline-CI
on:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup PHP Action, extensions and composer
      uses: shivammathur/setup-php@2.30.2
      with:
        extensions: mbstring, xml, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json
    - name: Cache multiple paths
      uses: actions/cache@v4.0.2
      with:
        # On met les vendirs en cache. Pour éviter que ce soit rafraîchir à chq fois, ajout de la clé key.
        # Rafraichissement du cache si et seult si le composer.lock a changé
        path: 
          vendor
        key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
              
    - name: "Composer install"
      run: composer install --no-interaction --no-progress
        # Install Symfony CLI
    - name: Symfony CLI
    # le pipe | permet d'enchaîner plusieurs commandes
      run: |
        curl -sS https://get.symfony.com/cli/installer | bash
        mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
    # CHeck des vulnérabilités
    - name: Symfony check Vulnerabilities
      run: symfony check:security
    # PHP CS FIXER
    - name: PHP-CS-FIXER
      run: |
        composer require friendsofphp/php-cs-fixer
        ./vendor/bin/php-cs-fixer fix --dry-run
          
